### ISSUE TITLE
Use `git status --porcelain` for working directory checking.

### ISSUE THREAD

**Issue by rwjblue** [kellyselden/git-diff-apply#43]
Using `git status` is error prone due to user customizations, we should use `git status --porcelain` instead.

For example, someone might have `git status` setup to emit the `--short` output by default which may not match the two regexps we check against in `src/is-git-clean.js`.

More details:

* [git status docs](https://git-scm.com/docs/git-status#git-status---porcelainltversiongt)

**Comment by kellyselden** [comment]
I'm trying to fix this now, but it doesn't detect detached HEAD like the old method. `porcelain` outputs everything OK in that case.

Maybe detached HEAD is something we don't care about, and continue updating as normal?
